### ISSUE TITLE
Create pull request for the Groovy project

### ISSUE THREAD

**Issue by etiennestuder** [mbjarland/groovy-streaming-template-engine#4]
It would be great to see this enhancement in the Groovy core.

The Groovy people seem open to it (see comment by Cédric Champeau on a pull request):
http://jira.codehaus.org/browse/GROOVY-3457?focusedCommentId=349126&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-349126

**Comment by mbjarland** [comment]
Pull request created at: 

https://github.com/groovy/groovy-core/pull/503

Waiting for a response. I would expect that some modifications might be needed (as in fixing issue #3 with $var style variable references) before the project maintainers accept the contribution. 

Closing issue as the first step has been taken and the ball is now in their court.
